#!/usr/bin/with-contenv bash

PUID=${PUID:-911}
PGID=${PGID:-911}

groupmod -o -g "$PGID" abc
usermod -o -u "$PUID" abc

echo '
-------------------------------------
  _   _                _ _           _
 | |_| |__   ___  __ _| | |__  _   _( )___
 | __| '_ \ / _ \/ _` | | '_ \| | | |// __|
 | |_| | | |  __/ (_| | | | | | |_| | \__ \
  \__|_| |_|\___|\__,_|_|_| |_|\__,_| |___/
  / _| | __ ___   _____ _ __
 | |_| |/ _` \ \ / / _ \ '__|
 |  _| | (_| |\ V /  __/ |
 |_| |_|\__,_| \_/ \___|_|
   ___  / _|
  / _ \| |_
 | (_) |  _|
  \___/|_|    ___   _                _                _
 |_   _\ \   / / | | | ___  __ _  __| | ___ _ __   __| |
   | |  \ \ / /| |_| |/ _ \/ _` |/ _` |/ _ \ '_ \ / _` |
   | |   \ V / |  _  |  __/ (_| | (_| |  __/ | | | (_| |
   |_|    \_/  |_| |_|\___|\__,_|\__,_|\___|_| |_|\__,_|

-------------------------------------'

echo '
GID/UID
-------------------------------------'
echo "
User uid:    $(id -u abc)
User gid:    $(id -g abc)
-------------------------------------
"

time32="$(date +%Y)"

if [[ "${time32}" == "1970" || "${time32}" == "1969" ]] && [ "$(uname -m)" == "armv7l" ]; then
  echo '
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

Your DockerHost is running an outdated version of libseccomp

To fix this, please visit https://docs.linuxserver.io/faq#libseccomp

Apps will not behave correctly without this

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
'
sleep infinity
fi

chown abc:abc /app
chown abc:abc /config
chown abc:abc /defaults
